import express from 'express';
import crypto from 'crypto';
import QRCode from 'qrcode';
import fs from 'fs/promises';
import path from 'path';

const app = express();
app.use(express.json({limit:'15mb'}));
app.get('/table-demo-qr.svg', async (req,res)=>{const svg=await QRCode.toString(`${publicBase(req)}/peppermint/t/12`,{type:'svg',margin:1,color:{dark:'#244633',light:'#ffffff'}});res.type('svg').send(svg)});
app.get('/',(_req,res)=>{res.set('Cache-Control','no-store');res.sendFile(process.cwd()+'/public/index.html')});
app.use(express.static('public',{setHeaders(res,filePath){if(filePath.endsWith('.html'))res.set('Cache-Control','no-store')}}));
const PORT=process.env.PORT||3000, BASE=process.env.PUBLIC_BASE_URL||`http://localhost:${PORT}`, orders=[];
const DATA_DIR=process.env.DATA_DIR||path.join(process.cwd(),'data'), COMPANIES_FILE=path.join(DATA_DIR,'companies.json');
const ALLOWED_DOC_TYPES=new Set(['application/pdf','image/jpeg','image/png']), MAX_DOC_BYTES=3*1024*1024, COMPANY_STATUSES=new Set(['submitted','under-review','ipg-submitted','approved','live','rejected']);
function publicBase(req){const local=h=>['localhost','127.0.0.1','[::1]'].includes(h),incoming=new URL(`http://${req.get('host')}`),configured=process.env.PUBLIC_BASE_URL;if(configured){try{const u=new URL(configured);if(['http:','https:'].includes(u.protocol)&&(!local(u.hostname)||local(incoming.hostname)))return u.origin}catch{}}return `${local(incoming.hostname)?req.protocol:'https'}://${incoming.host}`}
async function readCompanies(){try{return JSON.parse(await fs.readFile(COMPANIES_FILE,'utf8'))}catch(e){if(e.code==='ENOENT')return[];throw e}}
async function writeCompanies(c){await fs.mkdir(DATA_DIR,{recursive:true});const t=COMPANIES_FILE+'.tmp';await fs.writeFile(t,JSON.stringify(c,null,2));await fs.rename(t,COMPANIES_FILE)}
function cleanText(v,max=300){return String(v??'').trim().slice(0,max)}
function adminAllowed(req){const expected=process.env.PUNCHBOOK_ADMIN_KEY;if(!expected)return false;const supplied=req.get('x-admin-key')||req.query.key||'',a=Buffer.from(String(expected)),b=Buffer.from(String(supplied));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function requireAdmin(req,res,next){if(!process.env.PUNCHBOOK_ADMIN_KEY)return res.status(503).json({error:'Admin access is not configured. Set PUNCHBOOK_ADMIN_KEY on the server.'});if(!adminAllowed(req))return res.status(401).json({error:'Invalid admin key.'});next()}
function validateDocument(doc,label){if(!doc||typeof doc!=='object')return`${label} is required.`;const name=cleanText(doc.name,180),type=cleanText(doc.type,80),data=String(doc.data||'');if(!name||!data)return`${label} is required.`;if(!ALLOWED_DOC_TYPES.has(type))return`${label} must be PDF, JPG or PNG.`;if(Math.floor(data.length*3/4)>MAX_DOC_BYTES)return`${label} must be 3 MB or smaller.`;if(!/^[A-Za-z0-9+/=]+$/.test(data))return`${label} could not be read.`;return''}
function summariseCompany(c){const{documents,...safe}=c;return{...safe,documents:Object.fromEntries(Object.entries(documents||{}).map(([k,d])=>[k,{name:d.name,type:d.type,size:d.size}]))}}
const menu=[
{id:'m1',category:'Popular',name:'Truffle Chicken Pasta',desc:'Creamy parmesan sauce, mushrooms, grilled chicken.',price:2350,emoji:'🍝'},
{id:'m2',category:'Popular',name:'Pepper Beef Rice',desc:'Wok-seared beef, black pepper glaze and steamed rice.',price:1980,emoji:'🍛'},
{id:'m3',category:'Mains',name:'Crispy Chicken Burger',desc:'Buttermilk chicken, slaw, pickles and house sauce.',price:1750,emoji:'🍔'},
{id:'m4',category:'Mains',name:'Pesto Penne',desc:'Basil pesto, cherry tomato and parmesan.',price:1650,emoji:'🥗'},
{id:'m5',category:'Drinks',name:'Passion Fruit Mojito',desc:'Passion fruit, lime, mint and soda.',price:790,emoji:'🍹'},
{id:'m6',category:'Drinks',name:'Iced Spanish Latte',desc:'Double espresso, milk and condensed milk.',price:890,emoji:'🥤'},
{id:'m7',category:'Dessert',name:'Chocolate Lava Cake',desc:'Warm chocolate centre with vanilla ice cream.',price:1100,emoji:'🍰'}];
function orderId(){return'PB-'+Date.now().toString(36).toUpperCase().slice(-6)}function getEnv(n){return process.env[n]||''}
app.get('/api/menu',(_q,r)=>r.json({restaurant:{name:'Peppermint Café',area:'Colombo 03'},menu}));app.get('/api/orders',(_q,r)=>r.json([...orders].reverse()));
app.post('/api/orders',(req,res)=>{const{table='12',items=[],customer={},paymentMethod='card'}=req.body||{};const detailed=items.map(i=>{const p=menu.find(m=>m.id===i.id);return p?{...p,qty:Math.max(1,Number(i.qty)||1)}:null}).filter(Boolean);if(!detailed.length)return res.status(400).json({error:'Cart is empty'});const subtotal=detailed.reduce((s,i)=>s+i.price*i.qty,0),service=Math.round(subtotal*.05),total=subtotal+service,order={id:orderId(),table:String(table),items:detailed,subtotal,service,total,customer,paymentMethod,paymentStatus:'pending',orderStatus:'new',createdAt:new Date().toISOString()};orders.push(order);res.json(order)});
app.post('/api/orders/:id/status',(req,res)=>{const o=orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Order not found'});if(req.body.orderStatus)o.orderStatus=req.body.orderStatus;res.json(o)});
app.post('/api/companies',async(req,res)=>{try{const b=req.body||{},required=['companyName','registrationNumber','tradingName','businessType','registeredAddress','businessCategory','contactName','nicNumber','email','phone','contactRole','bankName','bankBranch','bankAccountName','bankAccountNumber'],missing=required.filter(k=>!cleanText(b[k]));if(missing.length)return res.status(400).json({error:`Missing required fields: ${missing.join(', ')}`});if(!b.declaration)return res.status(400).json({error:'Please accept the declaration.'});const errors=[validateDocument(b.documents?.businessRegistration,'Business registration certificate'),validateDocument(b.documents?.identityDocument,'NIC / passport'),validateDocument(b.documents?.bankProof,'Bank proof')].filter(Boolean);if(errors.length)return res.status(400).json({error:errors[0]});if(!/^\S+@\S+\.\S+$/.test(cleanText(b.email,180)))return res.status(400).json({error:'Enter a valid email address.'});const companies=await readCompanies(),now=new Date().toISOString(),reference='PBM-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase(),id=crypto.randomUUID(),documents={};for(const key of ['businessRegistration','identityDocument','bankProof']){const d=b.documents[key];documents[key]={name:cleanText(d.name,180),type:cleanText(d.type,80),size:Number(d.size)||0,data:String(d.data)}}const company={id,reference,status:'submitted',createdAt:now,updatedAt:now,companyName:cleanText(b.companyName,200),registrationNumber:cleanText(b.registrationNumber,100),tradingName:cleanText(b.tradingName,200),businessType:cleanText(b.businessType,100),registeredAddress:cleanText(b.registeredAddress,500),businessCategory:cleanText(b.businessCategory,120),contactName:cleanText(b.contactName,180),nicNumber:cleanText(b.nicNumber,100),email:cleanText(b.email,180),phone:cleanText(b.phone,80),contactRole:cleanText(b.contactRole,120),bankName:cleanText(b.bankName,120),bankBranch:cleanText(b.bankBranch,120),bankAccountName:cleanText(b.bankAccountName,180),bankAccountNumber:cleanText(b.bankAccountNumber,100),declaration:true,adminNotes:'',documents};companies.push(company);await writeCompanies(companies);res.status(201).json({ok:true,id,reference,status:company.status})}catch(e){console.error(e);res.status(500).json({error:'Could not save the application.'})}});
app.get('/api/admin/companies',requireAdmin,async(_q,res)=>{try{const companies=(await readCompanies()).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));res.json({companies:companies.map(summariseCompany)})}catch{res.status(500).json({error:'Could not load applications.'})}});
app.get('/api/admin/companies/:id',requireAdmin,async(req,res)=>{const c=(await readCompanies()).find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Company not found.'});res.json({company:summariseCompany(c)})});
app.patch('/api/admin/companies/:id/status',requireAdmin,async(req,res)=>{const status=cleanText(req.body?.status,40);if(!COMPANY_STATUSES.has(status))return res.status(400).json({error:'Invalid company status.'});const companies=await readCompanies(),c=companies.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Company not found.'});c.status=status;c.adminNotes=cleanText(req.body?.adminNotes,3000);c.updatedAt=new Date().toISOString();await writeCompanies(companies);res.json({ok:true,company:summariseCompany(c)})});
app.get('/api/admin/companies/:id/document/:doc',requireAdmin,async(req,res)=>{const c=(await readCompanies()).find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Company not found.'});const d=c.documents?.[req.params.doc];if(!d)return res.status(404).json({error:'Document not found.'});res.set('Content-Type',d.type||'application/octet-stream');res.set('Content-Disposition',`inline; filename="${String(d.name||'document').replace(/[\r\n"\\]/g,'_')}"`);res.set('Cache-Control','private, no-store');res.send(Buffer.from(d.data,'base64'))});
app.post('/api/payments/justpay/simulate',async(req,res)=>{const o=orders.find(x=>x.id===req.body.orderId);if(!o)return res.status(404).json({error:'Order not found'});o.paymentMethod='justpay';o.paymentStatus='paid';o.paymentRef='JP-DEMO-'+crypto.randomBytes(3).toString('hex').toUpperCase();res.json({ok:true,order:o,simulated:true})});
app.post('/api/payments/card',async(req,res)=>{const o=orders.find(x=>x.id===req.body.orderId);if(!o)return res.status(404).json({error:'Order not found'});const simulate=String(getEnv('SIMULATE_CARD')||'true').toLowerCase()!=='false',appId=getEnv('ONEPAY_APP_ID'),salt=getEnv('ONEPAY_HASH_SALT');if(simulate||!appId||!salt){o.paymentMethod='card';o.paymentStatus='paid';o.paymentRef='CARD-DEMO-'+crypto.randomBytes(3).toString('hex').toUpperCase();return res.json({ok:true,simulated:true,order:o})}const amount=Number(o.total).toFixed(2),currency='LKR',hash=crypto.createHash('sha256').update(appId+currency+amount+salt).digest('hex'),customer=o.customer||{},payload={app_id:appId,amount:Number(amount),currency,hash,reference:o.id,customer_first_name:customer.firstName||'Punchbook',customer_last_name:customer.lastName||'Guest',customer_phone_number:customer.phone||'+94770000000',customer_email:customer.email||'demo@punchbook.lk',transaction_redirect_url:`${publicBase(req)}/payment-return.html?order=${encodeURIComponent(o.id)}`,additionalData:JSON.stringify({orderId:o.id,table:o.table})};try{const response=await fetch(`${getEnv('ONEPAY_API_BASE')||'https://api.onepay.lk'}/v3/checkout/link/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json().catch(()=>({}));if(!response.ok)return res.status(502).json({error:'OnePay rejected checkout creation',provider:data});const redirectUrl=data?.data?.redirect_url||data?.redirect_url||data?.data?.gateway_url||data?.gateway_url,txId=data?.data?.ipg_transaction_id||data?.ipg_transaction_id||data?.transaction_id;if(txId)o.providerTransactionId=txId;o.paymentMethod='card';res.json({ok:true,simulated:false,redirectUrl,provider:data,order:o})}catch(e){res.status(502).json({error:'Could not reach OnePay',detail:String(e.message||e)})}});
app.post('/api/payments/verify',async(req,res)=>{const o=orders.find(x=>x.id===req.body.orderId);if(!o)return res.status(404).json({error:'Order not found'});if(!o.providerTransactionId||!getEnv('ONEPAY_APP_ID'))return res.json({ok:o.paymentStatus==='paid',order:o,simulated:true});try{const response=await fetch(`${getEnv('ONEPAY_API_BASE')||'https://api.onepay.lk'}/v3/transaction/status/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({app_id:getEnv('ONEPAY_APP_ID'),onepay_transaction_id:o.providerTransactionId})}),data=await response.json(),success=Boolean(data?.status===true||data?.data?.status===true);if(success)o.paymentStatus='paid';res.json({ok:success,order:o,provider:data})}catch(e){res.status(502).json({error:String(e.message||e)})}});
app.get('/qr',async(req,res)=>{const table=String(req.query.table||'12'),url=`${publicBase(req)}/peppermint/t/${encodeURIComponent(table)}`,svg=await QRCode.toString(url,{type:'svg',margin:2,width:440});res.type('html').send(`<!doctype html><html><head><meta name="viewport" content="width=device-width"><style>body{font-family:Inter,system-ui;background:#f6f3ec;display:grid;place-items:center;min-height:100vh;margin:0}.card{background:white;padding:38px;border-radius:28px;text-align:center;max-width:430px}svg{max-width:100%;height:auto}</style></head><body><div class="card"><h2>Peppermint Café</h2><p>Table ${table}</p>${svg}<h2>Scan to order</h2><p>No app needed · Powered by Punchbook</p></div></body></html>`)});
app.get(['/peppermint','/peppermint/t/:table','/r/:restaurant/t/:table'],(_q,r)=>r.sendFile(process.cwd()+'/public/peppermint.html'));app.get('/admin',(_q,r)=>r.sendFile(process.cwd()+'/public/admin.html'));app.get(['/signup','/join','/onboarding'],(_q,r)=>r.sendFile(process.cwd()+'/public/onboarding.html'));app.get(['/admin/companies','/companies-admin'],(_q,r)=>r.sendFile(process.cwd()+'/public/companies-admin.html'));
app.listen(PORT,()=>console.log(`Punchbook prototype running at ${BASE}`));